events {}

http {

    upstream bpscnotes_api {
        server bpscnotes-api:5000;
        keepalive 32;
    }

    upstream bpscnotes_admin {
        server 172.17.0.1:3000;
        keepalive 16;
    }

    limit_req_zone $binary_remote_addr zone=otp_limit:10m rate=5r/m;
    limit_req_zone $binary_remote_addr zone=login_limit:10m rate=20r/m;
    limit_req_zone $binary_remote_addr zone=api_limit:20m rate=100r/m;

    limit_conn_zone $binary_remote_addr zone=conn_limit:10m;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;

    keepalive_timeout 65;

    include /etc/nginx/conf.d/*.conf;
}