events {}

http {

    upstream bpscnotes_api {
        server 127.0.0.1:5000;
        keepalive 32;
    }

    upstream bpscnotes_admin {
        server 127.0.0.1:3000;
        keepalive 16;
    }

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;

    keepalive_timeout 65;

    include /etc/nginx/conf.d/*.conf;
}