# ================= API =================
server {
    listen 80;
    server_name api.bpscnotes.in;

    location / {
        proxy_pass http://api:5000;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

# ================= ADMIN =================
server {
   listen 80;
    server_name admin.bpscnotes.in;

    # API calls from admin
    location /api/ {
        proxy_pass http://api:5000/api/;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Admin UI
    location / {
        proxy_pass http://172.17.0.1:3000;

        proxy_http_version 1.1;

        proxy_set_header Host $host;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
# HTTP → HTTPS redirect
#server {
 #   listen 80;
  #  server_name admin.bpscnotes.in;
#
 #   return 301 https://$host$request_uri;
#}

# HTTPS
#server {
 #   listen 443 ssl;
  #  server_name admin.bpscnotes.in;

   # ssl_certificate /etc/letsencrypt/live/admin.bpscnotes.in/fullchain.pem;
    #ssl_certificate_key /etc/letsencrypt/live/admin.bpscnotes.in/privkey.pem;

    #location /api/ {
     #   proxy_pass http://api:5000/api/;
    #}

    #location / {
     #   proxy_pass http://172.17.0.1:3000;

      #  proxy_http_version 1.1;
     #   proxy_set_header Host $host;
    #    proxy_set_header X-Real-IP $remote_addr;
   #     proxy_set_header Upgrade $http_upgrade;
  #      proxy_set_header Connection "upgrade";
 #   }
#}
