// Google Play external-transaction reporting for the user choice billing
// program (India). When a user picks "pay with Cashfree" on Google's
// billing-choice screen, the Play Billing Library hands the app an
// externalTransactionToken; every Cashfree payment made under that token
// must be reported to Play within 24h via
// purchases.externaltransactions.createexternaltransaction, or the app is
// out of program compliance (Google bills its reduced service fee off
// these reports).
//
// The endpoint isn't generated by the installed googleapis@144 client, so
// this goes through the raw authenticated client — same pattern as
// gplay-purchase.util.ts / gplay-catalog.util.ts.

import { getPlayAuthClients } from './gplay-auth.util';

// Prices in the app are GST-inclusive; Play wants pre-tax + tax reported
// separately. Rate is overridable because digital-goods GST could change.
function gstRatePct(): number {
  const parsed = Number(process.env.GPLAY_EXTERNAL_TX_GST_PCT);
  return Number.isFinite(parsed) && parsed >= 0 && parsed < 100 ? parsed : 18;
}

export interface ExternalTransactionReport {
  // Our unique id for the transaction — the Cashfree order id fits Google's
  // constraints (1-63 chars of [a-zA-Z0-9_-]; cashfreeReceiptId() emits
  // <=50 chars of that alphabet) and is already unique per payment.
  externalTransactionId: string;
  externalTransactionToken: string;
  // Gross INR actually captured, straight from Cashfree's verified payment
  // record — never a client-supplied amount.
  amountInr: number;
  // Cashfree payment_time (ISO, +05:30 offset). Defaults to now if absent.
  transactionTime?: string | null;
}

// Never throws — reporting is a post-payment side effect and must not undo
// an entitlement that's already been granted (same contract as
// acknowledgeOneTimeProductPurchase). Returns true when Play accepted the
// report (or already had it), so callers can stamp reported_at.
export async function reportExternalTransaction(report: ExternalTransactionReport): Promise<boolean> {
  try {
    const { rawClient, packageName } = await getPlayAuthClients();

    const externalTransactionId = report.externalTransactionId
      .replace(/[^a-zA-Z0-9_-]/g, '_')
      .substring(0, 63);

    const gross = Number(report.amountInr);
    if (!Number.isFinite(gross) || gross <= 0) {
      console.error(`Play external-transaction report skipped: bad amount ${report.amountInr} for ${externalTransactionId}`);
      return false;
    }
    const rate         = gstRatePct();
    const preTaxMicros = Math.round((gross / (1 + rate / 100)) * 1_000_000);
    const taxMicros    = Math.round(gross * 1_000_000) - preTaxMicros;

    let transactionTime: string;
    try {
      transactionTime = new Date(report.transactionTime || Date.now()).toISOString();
    } catch {
      transactionTime = new Date().toISOString();
    }

    const url =
      `https://androidpublisher.googleapis.com/androidpublisher/v3/applications/${encodeURIComponent(packageName)}` +
      `/externalTransactions?externalTransactionId=${encodeURIComponent(externalTransactionId)}`;

    await rawClient.request({
      url,
      method: 'POST',
      data: {
        transactionTime,
        originalPreTaxAmount: { priceMicros: String(preTaxMicros), currency: 'INR' },
        originalTaxAmount:    { priceMicros: String(taxMicros),    currency: 'INR' },
        userTaxAddress:       { regionCode: 'IN' },
        // Cashfree plans here are single up-front charges for a fixed
        // period (no auto-renew mandate), so subscriptions report as
        // one-time transactions too — recurringTransaction is only for
        // charges Google should expect to repeat without a new token.
        oneTimeTransaction:   { externalTransactionToken: report.externalTransactionToken },
      },
    });
    return true;
  } catch (e: any) {
    const status = e?.response?.status;
    // 409 = this externalTransactionId was already reported (e.g. confirm
    // and webhook both fired, or the retry cron raced a live confirm) —
    // that's success for our purposes.
    if (status === 409) return true;
    console.error(
      `Play external-transaction report failed for ${report.externalTransactionId}:`,
      e?.response?.data ?? e?.message ?? e,
    );
    return false;
  }
}

export type ExternalTransactionTable = 'subscriptions' | 'course_purchases' | 'material_purchase_orders';

// Shared store → report → stamp orchestration used by all three purchase
// flows (courses, study materials, subscriptions) so the compliance logic
// lives in exactly one place. Stores the token on the row (first writer
// wins), reports to Play, and stamps external_transaction_reported_at on
// success so the retry cron skips the row. Never throws — callers invoke
// it fire-and-forget after the entitlement is already granted.
export async function storeReportAndStampExternalTransaction(
  query: (sql: string, params?: any[]) => Promise<any>,
  table: ExternalTransactionTable,
  rowId: string,
  report: ExternalTransactionReport,
): Promise<void> {
  try {
    await query(
      `UPDATE ${table} SET external_transaction_token=$1
       WHERE id=$2 AND external_transaction_token IS NULL`,
      [report.externalTransactionToken, rowId]
    );
    const reported = await reportExternalTransaction(report);
    if (reported) {
      await query(
        `UPDATE ${table} SET external_transaction_reported_at=NOW() WHERE id=$1`,
        [rowId]
      );
    }
  } catch (err: any) {
    console.error(
      `External-transaction store/report failed: table=${table} row=${rowId} err=${err?.message}`
    );
  }
}
